# Api Keys
keys:
  llm_api_key : "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"

# Paths
paths : 
  ontology_local_path : "C:\\Users\\lucmi\\Documents\\Opdrachten\\IAG-Project\\intelligent_agents.rdf"
  protege_path : "C:\\Users\\lucmi\\Downloads\\Protege-5.6.4-win\\Protege-5.6.4\\jre\\bin\\java.exe"

# LLM specs
model_specs:
  model_type : "llama3-8b-8192"
  temperature : 0.2

# Ontology specs