# Api Keys
keys:
  llm_api_key : "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"

# Paths
paths : 
  ontology_local_path : "ontology.rdf"
  protege_path : "C:\\Program Files\\Protege-5.6.4\\jre\\bin\\java.exe"

# LLM specs
model_specs:
  model_type : "llama3-8b-8192"
  temperature : 0.2

# Ontology specs
ontology_llm_mapper:
  model_type : "llama3-8b-8192" #"claude-3-opus-20240229"